image: python:3.7.2-alpine

stages:
  - build
  - test
  - deploy

services:
   - docker:18-dind

variables:
   DOCKER_IMAGE: francetransfert-upload-api:0.0.1     
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2

before_script:
  - pip install --upgrade pip
  - pip3 install awscli --upgrade
  - apk --no-cache add curl
  - apk add docker

smapi:build:
  stage: build
  only:
    - master
    - develop
    - automation
  tags:
    - squads-aws
  script:
    - echo "Pipeline Build stage ..."
    - docker build -t ${DOCKER_REGISTRY_BASE_URI}/$DOCKER_IMAGE .
    - eval $(aws ecr get-login --no-include-email)
    - docker push ${DOCKER_REGISTRY_BASE_URI}/$DOCKER_IMAGE

smapi:deploy:
  stage: deploy
  only:
    - master
    - develop
    - automation
  tags: 
    - squads-aws
  script:
    - echo "Pipeline Deploy stage ..."
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${K8S_CLUSTER_NAME}
    - kubectl delete -f k8s/francetransfert-upload-api-service.yml -n skills-staging  
    - kubectl apply -f k8s/francetransfert-upload-api-service.yml -n skills-staging
